### ISSUE TITLE
first run errors

### ISSUE THREAD

**Issue by squalou** [aenany/google-hangouts-chat-linux#21]
**Describe the bug**
js errors at very first run.
Not such a big deal

Error due to missing file : .config/google-hangouts-chat-linux.json

**To Reproduce**
- Remove (move away) above file
- yarn start

**Expected behavior**

If no fil present, init an empty one and don't complain

**Comment by aenany** [comment]
@squalou I will take a look when I have a chance, should be an easy fix.

**Comment by aenany** [comment]
@squalou https://github.com/aenany/google-hangouts-chat-linux/pull/22 I have merged this into master
